### ISSUE TITLE
Run Variable Sanity Checks Failed

### ISSUE THREAD

**Issue by funky81** [gshipley/installrhel#2]
Hi, I'm trying Openshift 3.11 to install using this script but got failed in steps

> ansible-playbook -i inventory.ini openshift-ansible/playbooks/prerequisites.yml

it said like below

> TASK [Run variable sanity checks] **************************************************************************************************************************************
> fatal: [10.250.19.11]: FAILED! => {"msg": "last_checked_host: 10.250.19.11, last_checked_var: openshift_master_identity_providers;Found removed variables: openshift_node_kubelet_args is replaced by openshift_node_groups[<item>].edits; "}
> 

Any solutions for this error? 

Thanks

**Comment by slaterx** [comment]
This was fixed by https://github.com/okd-community-install/installrhel/pull/5
